### ISSUE TITLE
Sometimes, not regularly on <F3> command the following error occurs

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#402]
2024-12-28 09:35:23,844 - api.deribit.ws - INFO - Heartbeat established.
2024-12-28 09:35:23,865 - api.deribit.ws - INFO - ws subscription - Portfolio - channel - user.portfolio.any
2024-12-28 09:35:23,867 - api.deribit.ws - INFO - ws subscription - User changes - channel - user.changes.any.any.raw
Traceback (most recent call last):
  File "/home/rmn/241228/api/deribit/ws.py", line 298, in __on_message
    id = message["id"]
KeyError: 'id'

2024-12-28 09:35:23,948 - api.deribit.ws - INFO - Websocket closed.

**Comment by nikolayromenskiy** [comment]
The websocket sends: {'jsonrpc': '2.0', 'error': {'code': -32600, 'message': 'request entity too large'}, 'usIn': 1735470238752669, 'usOut': 1735470238752706, 'usDiff': 37, 'testnet': True}

Add the following subscription line to raise the error:

BTC-10JAN25_series, PAXG_USDC-27JUN25_series, BTC-27DEC24_series, BTC-28MAR25_series, BTC-25OCT24_series, BNB_USDC-11OCT24_series, SOL_USDC-10OCT24_series, MATIC_USDC-11OCT24_series, BTC-DSTDC-27DEC24_29NOV24_series, SOL_USDC-1OCT24_series, ETH-1OCT24_series, ETH-25OCT24-, ETH-8NOV24-

**Comment by evgrmn** [comment]
Fixed in commit e1f4e43 and commit da247de. Also added error handling to websocket when it does not send a request ID. Now errors like "request entity too large" will appear in the info section and in the log file.

This issue is only partially resolved, as the "request entity too large" error is still possible when subscribing to many instruments, especially many options that have up to hundreds or even thousands of put and call strikes in total, both in the order book and in the ticker. This can be solved by splitting the subscriptions into parts.

**Comment by nikolayromenskiy** [comment]
The current realization 99% closes the issue. At least one-time subscription to all the Deribit's futures is possible, I think.
